//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.FMS.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string TransActionMakerUsername { get; set; }
        public bool TransactionDecision { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionServiceID { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
